### ISSUE TITLE
How to get a correct json-key file in bigquery?

### ISSUE THREAD

**Issue by Youngsoo77** [kkamkou/gitmostwanted.com#173]
I had an error. 

When I run this project, some problem appear.

The message is shown below.

```sh
[2016-12-01 08:00:00,047: ERROR/PoolWorker-5] Task gitmostwanted.tasks.repo_most_starred.most_starred_day[11053e10-1230-4f3f-9ac2-5781b7b45a5c] raised unexpected: ValueError('Unexpected credentials type', None, 'Expected', 'service_account')
Traceback (most recent call last):
  File "/Users/young.soo/.pyenv/versions/3.4.5/envs/oss_big_query/lib/python3.4/site-packages/celery/app/trace.py", line 368, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/gitmostwanted/services/celery.py", line 14, in __call__
    return super().__call__(*args, **kwargs)
  File "/Users/young.soo/.pyenv/versions/3.4.5/envs/oss_big_query/lib/python3.4/site-packages/celery/app/trace.py", line 623, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/gitmostwanted/tasks/repo_most_starred.py", line 30, in most_starred_day
    """.format((date.today() - timedelta(1)).strftime('%Y%m%d'))
  File "/opt/gitmostwanted/tasks/repo_most_starred.py", line 80, in most_starred_sync
    service = bigquery.instance(app)
  File "/opt/gitmostwanted/services/bigquery.py", line 7, in instance
    return ServiceGmw(cfg['json_key_path'], cfg['project_id'])
  File "/opt/gitmostwanted/lib/bigquery/service.py", line 28, in __init__
    json_key_path, 'bigquery', 'v2', 'https://www.googleapis.com/auth/bigquery'
  File "/opt/gitmostwanted/lib/bigquery/service.py", line 14, in __init__
    auth = ServiceAccountCredentials.from_json_keyfile_name(json_key_path, scope)
  File "/Users/young.soo/.pyenv/versions/3.4.5/envs/oss_big_query/lib/python3.4/site-packages/oauth2client/service_account.py", line 223, in from_json_keyfile_name
    revoke_uri=revoke_uri)
  File "/Users/young.soo/.pyenv/versions/3.4.5/envs/oss_big_query/lib/python3.4/site-packages/oauth2client/service_account.py", line 172, in _from_parsed_json_keyfile
    'Expected', client.SERVICE_ACCOUNT)
ValueError: ('Unexpected credentials type', None, 'Expected', 'service_account')
```

I think that I put a wrong json key. But I do not know How to get a correct key.

Could you give me a hint?

Kind Regards.

- youngsoo

**Comment by kkamkou** [comment]
First, you need to enable the big-query service. Then, open this [dataset](https://bigquery.cloud.google.com/table/githubarchive:day.20150101). The next step is to go to `https://console.developers.google.com` and click the `Create credentials` button with the `service account` type. At the end you'll see something like this:
![](http://2ka.by/tmp/screenshots/2016-12-01-ac10beb.png)

**Comment by Youngsoo77** [comment]
Dear kkamkou

Thank you for your help.

Your email helps me a lot.

now I can run your project.

Thanks a lot.

youngsoo

2016-12-01 9:37 GMT+09:00 Kanstantsin Kamkou <notifications@github.com>:
